const defaultTheme = require("tailwindcss/defaultTheme");

module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./{home,services,reviews,contact}/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          DEFAULT: "#E8A838",
          50: "#FEF7E8",
          100: "#FDECC5",
          200: "#F9D78A",
          300: "#F3C05A",
          400: "#E8A838",
          500: "#D4911E",
          600: "#B17416",
          700: "#8A5911",
          800: "#6B440D",
          900: "#4D310A",
          950: "#2E1D06",
        },
        dark: "#0A0A0A",
        bg:         'rgb(var(--c-bg) / <alpha-value>)',
        surface:    {
          DEFAULT: 'rgb(var(--c-surface) / <alpha-value>)',
          card: 'rgb(var(--c-surface-card) / <alpha-value>)',
          "card-hover": "#1A1A1A",
          border: 'rgb(var(--c-surface-border) / <alpha-value>)',
          light: "#FAFAF9",
          muted: "#F5F5F4",
          "border-light": "#E7E5E4",
        },
        surface2:   'rgb(var(--c-surface-2) / <alpha-value>)',
        border:     'rgb(var(--c-border) / <alpha-value>)',
        'border-bold': 'rgb(var(--c-border-bold) / <alpha-value>)',
        accent:     'rgb(var(--c-accent) / <alpha-value>)',
        'accent-dim': 'rgb(var(--c-accent-dim) / <alpha-value>)',
        heading:    'rgb(var(--c-heading) / <alpha-value>)',
        body:       'rgb(var(--c-body) / <alpha-value>)',
        muted:      'rgb(var(--c-muted) / <alpha-value>)',
        page: "rgb(var(--c-page) / <alpha-value>)",
        "nav-scrolled": "rgb(var(--c-nav-scrolled) / <alpha-value>)",
        menu: "rgb(var(--c-menu) / <alpha-value>)",
      },
      fontFamily: {
        display: 'var(--font-display)',
        mono:    'var(--font-mono)',
        body:    'var(--font-body)',
      },
      fontSize: {
        "display-xl": ["clamp(3rem, 8vw, 6rem)", { lineHeight: "0.95", letterSpacing: "0.04em", fontWeight: "400" }],
        "display-lg": ["clamp(2.5rem, 6vw, 4.5rem)", { lineHeight: "1", letterSpacing: "0.03em", fontWeight: "400" }],
        "display-md": ["clamp(2rem, 4vw, 3rem)", { lineHeight: "1.1", letterSpacing: "0.02em", fontWeight: "400" }],
        "display-sm": ["clamp(1.5rem, 3vw, 2rem)", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-lg": ["1.125rem", { lineHeight: "1.65" }],
        "body-md": ["1rem", { lineHeight: "1.65" }],
        "body-sm": ["0.875rem", { lineHeight: "1.6" }],
        label: ["0.75rem", { lineHeight: "1.4", letterSpacing: "0.12em", fontWeight: "500" }],
      },
      borderRadius: {
        DEFAULT: '0px',
        none:    '0px',
        sm:      '0px',
        md:      '0px',
        lg:      '0px',
        xl:      '0px',
        '2xl':   '0px',
        '3xl':   '0px',
        '4xl':   '0px',
        full:    '9999px',
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-brand": "linear-gradient(135deg, #E8A838 0%, #D4911E 100%)",
        "noise": "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.65' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)' opacity='0.04'/%3E%3C/svg%3E\")",
      },
      animation: {
        "fade-in": "fadeIn 0.6s ease-out forwards",
        "fade-up": "fadeUp 0.7s ease-out forwards",
        "slide-in-right": "slideInRight 0.5s ease-out forwards",
        "scale-in": "scaleIn 0.5s ease-out forwards",
        "pulse-slow": "pulse 3s ease-in-out infinite",
        "marquee": "marquee 30s linear infinite",
      },
      keyframes: {
        fadeIn: { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        fadeUp: { "0%": { opacity: "0", transform: "translateY(24px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        slideInRight: { "0%": { opacity: "0", transform: "translateX(-24px)" }, "100%": { opacity: "1", transform: "translateX(0)" } },
        scaleIn: { "0%": { opacity: "0", transform: "scale(0.95)" }, "100%": { opacity: "1", transform: "scale(1)" } },
        marquee: { "0%": { transform: "translateX(0)" }, "100%": { transform: "translateX(-50%)" } },
      },
      transitionTimingFunction: {
        "out-expo": "cubic-bezier(0.16, 1, 0.3, 1)",
        "silk": "cubic-bezier(0.062, 0.165, 0.225, 0.86)",
        "whip": "cubic-bezier(0.11, 0.494, 0.318, 0.852)",
      },
    },
  },
};
